name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Cambia esta rama si usas otra para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      - name: Deploy files to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no usuario@147.79.84.240 "mkdir -p ~/mi-proyecto"
          rsync -avz --delete ./ u916011081@srv123.hostinger.com:~/public_html
